import { assets } from "./assets";

export type ZoneId = "education" | "healthcare" | "business" | "dailyLife";
export type ChoiceKind = "responsible" | "dangerous";

export type Zone = {
  id: ZoneId;
  areaTitle: string;
  placeName: string;
  background: string;
  problem: string;
  question: string;
  opportunity: string;
  risk: string;
  audienceQuestion: string;
  responsibleChoice: string;
  dangerousChoice: string;
  responsibleConsequence: string;
  dangerousConsequence: string;
  responsibleWhyItMatters: string;
  dangerousWhyItMatters: string;
  checkpointLesson: string;
  humanControlRule: string;
};

export const zones: Zone[] = [
  {
    id: "education",
    areaTitle: "Education",
    placeName: "The Classroom Ruins",
    background: assets.education,
    problem: "AI can be a study partner, but it can also make students skip real thinking.",
    question: "You have to write an essay. How will you use AI?",
    opportunity: "AI can explain difficult topics, check grammar, and create practice exercises.",
    risk: "Students may use AI to cheat or stop thinking for themselves.",
    audienceQuestion: "Should AI write the essay or help us understand it?",
    responsibleChoice: "Use AI to understand the topic and write the essay yourself.",
    dangerousChoice: "Ask AI to write everything and submit it as your own work.",
    responsibleConsequence: "AI supports learning and helps the student improve.",
    dangerousConsequence: "AI replaces learning and weakens critical thinking.",
    responsibleWhyItMatters: "Learning stays real when AI helps you understand and you still do the work.",
    dangerousWhyItMatters: "Submitting AI work as your own may feel easy, but it hurts honesty and skill.",
    checkpointLesson: "AI should support learning, not replace thinking.",
    humanControlRule: "The student must choose the ideas and write the final essay.",
  },
  {
    id: "healthcare",
    areaTitle: "Healthcare",
    placeName: "The Healing Camp",
    background: assets.healthcare,
    problem: "AI can find patterns in medical data, but health choices affect real people.",
    question: "A doctor uses AI to analyze a medical image. What should happen next?",
    opportunity: "AI can help doctors analyze data and detect diseases earlier.",
    risk: "AI can make mistakes, and private medical data can be misused.",
    audienceQuestion: "Should AI make the medical decision alone?",
    responsibleChoice: "The doctor checks the result and makes the final decision.",
    dangerousChoice: "The AI makes the medical decision alone.",
    responsibleConsequence: "AI supports doctors while humans stay in control.",
    dangerousConsequence: "Serious medical decisions become risky without human judgment.",
    responsibleWhyItMatters: "AI is useful in healthcare when trained people check it and protect patients.",
    dangerousWhyItMatters: "A wrong medical choice can hurt a person, so AI should not decide alone.",
    checkpointLesson: "AI can help doctors, but people must make final decisions.",
    humanControlRule: "Doctors must review AI results and make the final decision.",
  },
  {
    id: "business",
    areaTitle: "Business",
    placeName: "The Market of Machines",
    background: assets.business,
    problem: "AI can make work faster, but companies must protect people, privacy, and trust.",
    question: "A company wants to use AI to save time. What is the responsible way?",
    opportunity: "AI helps companies save time, answer customer questions, and analyze sales.",
    risk: "AI can replace jobs and collect too much customer data.",
    audienceQuestion: "Should a company replace workers immediately?",
    responsibleChoice: "Use AI for simple tasks and train workers for new skills.",
    dangerousChoice: "Replace workers immediately without support or training.",
    responsibleConsequence: "AI improves efficiency while people are protected.",
    dangerousConsequence: "AI becomes a threat to workers and trust.",
    responsibleWhyItMatters: "A responsible company uses AI to improve work and help people learn new skills.",
    dangerousWhyItMatters: "Replacing workers without support can hurt people, customers, and trust.",
    checkpointLesson: "AI can save time, but companies must protect people and privacy.",
    humanControlRule: "Leaders must use AI with worker support, clear rules, and privacy protection.",
  },
  {
    id: "dailyLife",
    areaTitle: "Daily Life",
    placeName: "The Mirror Lake",
    background: assets.dailyLife,
    problem: "AI tools are part of daily life, so people need calm judgment before trusting them.",
    question: "You see shocking news online that may be generated by AI. What will you do?",
    opportunity: "AI helps with navigation, translation, recommendations, and daily tasks.",
    risk: "People may depend too much on AI or believe false information.",
    audienceQuestion: "Should we share shocking news without checking it?",
    responsibleChoice: "Check the source before believing or sharing it.",
    dangerousChoice: "Share it immediately without checking.",
    responsibleConsequence: "Critical thinking protects the user from fake information.",
    dangerousConsequence: "False information spreads faster and becomes dangerous.",
    responsibleWhyItMatters: "Checking sources slows false information and keeps your thinking independent.",
    dangerousWhyItMatters: "Sharing false AI content can confuse people and spread fear quickly.",
    checkpointLesson: "AI tools are useful, but information must be checked.",
    humanControlRule: "The user must check important information before trusting or sharing it.",
  },
];
